### ISSUE TITLE
刮刮乐 可否在一个页面创建多个刮刮乐

### ISSUE THREAD

**Issue by getChange** [o2team/wxapp-market#9]
产品有一个需求 需要在同一个页面添加多个刮刮卡 可是我创建了 却只有最后一个可以使用 别的都无法使用

**Comment by gluu1** [comment]
目前只实例了一个 canvas 对象进行绘制，这块可以后续考虑支持一下

**Comment by getChange** [comment]
> 目前只实例了一个 canvas 对象进行绘制，这块可以后续考虑支持一下

还有一个问题，就是为什么会有些机型使用刮奖，会刮不干净，图片还没刮完，就会直接走到callback函数内

**Comment by gluu1** [comment]
@getChange  刮刮乐有范围检测清除
![image](https://user-images.githubusercontent.com/7833110/66794780-369bdc00-ef35-11e9-9161-6f9749146a15.png)
